/**
 * Client-side TypeScript compilation for GUI islands.
 *
 * Uses esbuild (already installed as a transitive dep of @fresh/core)
 * to bundle island .tsx files into browser-ready JS with proper browser
 * platform settings (no `node:process`, no Node.js builtins).
 *
 * @module
 */
import * as esbuild from "npm:esbuild@~0.25.5";
import type { Plugin } from "npm:esbuild@~0.25.5";
import * as path from "jsr:@std/path@^1";
import manifest from "./manifest.json" with { type: "json" };

const IS_REMOTE = !import.meta.url.startsWith("file:");
const GUI_DIR = IS_REMOTE
  ? new URL(".", import.meta.url).href
  : path.dirname(path.fromFileUrl(import.meta.url));

/**
 * JSR resolves import maps at publish time, rewriting bare specifiers like
 * "preact" into "npm:preact@^10". esbuild doesn't understand the npm:
 * protocol, so this plugin intercepts those imports, marks them external,
 * and rewrites them back to bare specifiers for the browser import map.
 */
const denoNpmExternalPlugin: Plugin = {
  name: "deno-npm-external",
  setup(build) {
    build.onResolve({ filter: /^npm:preact/ }, (args) => {
      const bare = args.path
        .replace(/^npm:/, "")
        .replace(/@[^/]*/, "");
      return { path: bare, external: true };
    });
  },
};

/** Compiled island JS keyed by island name (e.g., "sse-provider"). */
export type CompiledIslands = ReadonlyMap<string, string>;

/**
 * When running from a remote URL (e.g. JSR), Deno.readDir and esbuild
 * can't access the source files directly. Mirror the gui/ subtree into
 * a temp directory so esbuild can resolve all imports locally.
 * File list comes from manifest.json (generated by gen-gui-manifest.ts).
 */
const mirrorToTemp = async (): Promise<string> => {
  const tmp = await Deno.makeTempDir({ prefix: "ralphmania-gui-" });
  await Promise.all((manifest as string[]).map(async (rel) => {
    const url = new URL(rel, GUI_DIR);
    const resp = await fetch(url);
    if (!resp.ok) throw new Error(`Failed to fetch ${url}: ${resp.status}`);
    const text = await resp.text();
    const dest = path.join(tmp, rel);
    await Deno.mkdir(path.dirname(dest), { recursive: true });
    await Deno.writeTextFile(dest, text);
  }));
  return tmp;
};

/** Compile all island entry points to browser JS. */
export const compileIslands = async (): Promise<CompiledIslands> => {
  const localGuiDir = IS_REMOTE ? await mirrorToTemp() : GUI_DIR;
  const cleanup = IS_REMOTE
    ? () => Deno.remove(localGuiDir, { recursive: true })
    : undefined;

  const islandsDir = path.join(localGuiDir, "islands");
  const entryPoints: string[] = [];
  for await (const entry of Deno.readDir(islandsDir)) {
    if (entry.isFile && entry.name.endsWith(".tsx")) {
      entryPoints.push(path.join(islandsDir, entry.name));
    }
  }

  const result = await esbuild.build({
    entryPoints,
    bundle: true,
    splitting: true,
    format: "esm",
    platform: "browser",
    target: "es2022",
    outdir: "out",
    write: false,
    plugins: [denoNpmExternalPlugin],
    // Preact is externalized — loaded via import map in the HTML.
    external: ["preact", "preact/*"],
    define: {
      "process.env.NODE_ENV": '"production"',
    },
    jsx: "automatic",
    jsxImportSource: "preact",
  });

  const compiled = new Map<string, string>();
  for (const file of result.outputFiles) {
    const name = path.basename(file.path);
    compiled.set(name, file.text);
  }

  await esbuild.stop();
  await cleanup?.();
  return compiled;
};
